### ISSUE TITLE
Liberty is unable to connect

### ISSUE THREAD

**Issue by ch2ch3** [ustwo/docker-ruby#2]
When using this as a base image vs the official Ruby 2.2, I get the following error message:

```
usr/lib/ruby/2.2.0/net/http.rb:923:in `connect': SSL_connect returned=1 errno=0 state=error: certificate verify failed (Faraday::SSLError)
	from /usr/lib/ruby/2.2.0/net/http.rb:923:in `block in connect'
	from /usr/lib/ruby/2.2.0/timeout.rb:73:in `timeout'
	from /usr/lib/ruby/2.2.0/net/http.rb:923:in `connect'
	from /usr/lib/ruby/2.2.0/net/http.rb:863:in `do_start'
	from /usr/lib/ruby/2.2.0/net/http.rb:852:in `start'
	from /usr/lib/ruby/2.2.0/net/http.rb:1375:in `request'
	from /usr/lib/ruby/2.2.0/net/http.rb:1133:in `get'
	from /home/ustwo/vendor/bundle/ruby/2.2.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:80:in `perform_request'
	from /home/ustwo/vendor/bundle/ruby/2.2.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:40:in `block in call'
	from /home/ustwo/vendor/bundle/ruby/2.2.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:87:in `with_net_http_connection'
	from /home/ustwo/vendor/bundle/ruby/2.2.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:32:in `call'
	from /home/ustwo/vendor/bundle/ruby/2.2.0/gems/faraday-0.9.2/lib/faraday/request/url_encoded.rb:15:in `call'
	from /home/ustwo/vendor/bundle/ruby/2.2.0/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
	from /home/ustwo/vendor/bundle/ruby/2.2.0/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
	from /home/ustwo/vendor/bundle/ruby/2.2.0/gems/faraday-0.9.2/lib/faraday/connection.rb:140:in `get'
	from /home/ustwo/liberty-0.6.6/lib/liberty/session.rb:222:in `get_session_id'
	from /home/ustwo/liberty-0.6.6/lib/liberty/session.rb:19:in `initialize'
	from /home/ustwo/liberty-0.6.6/lib/liberty/core.rb:72:in `new'
	from /home/ustwo/liberty-0.6.6/lib/liberty/core.rb:72:in `connect'
	from /home/ustwo/liberty-0.6.6/lib/liberty/collection.rb:24:in `initialize'
	from scripts/rogo-sync.rb:25:in `new'
	from scripts/rogo-sync.rb:25:in `<main>'
```

**Comment by arnau** [comment]
@ch2ch3 looks like you are missing https://pkgs.alpinelinux.org/package/main/x86_64/ca-certificates

Given that the aim of using an Alpine based image is to keep things small, I would suggest you install this package in your image.

**Comment by ch2ch3** [comment]
@arnau `ca-certificates` is already installed (as part of `curl`). I tried manually installing it anyway but the error persists.

http://stackoverflow.com/a/32363597 is this relevant?
